export const parseNum = (val) => {
  if (val === undefined || val === null || val === "") return 0;
  return parseFloat(String(val).replace(/,/g, "")) || 0;
};

export const fmt = (val) => val !== null && val !== undefined ? "$" + Math.round(val).toLocaleString("en-NZ") : "—";
export const fmtPct = (val) => val !== null && val !== undefined ? val.toFixed(2) + "%" : "—";

export const DEFAULTS = {
  propertyAddress: "",
  propertyDescription: "",
  propertyValue: "750000",
  purchaseCosts: "3840",
  grossRentWeekly: "700",
  rentalExpensesPercent: "29.77",
  cashInvested: "75000",
  loanCosts: "7224",
  equityInvested: "0",
  interestRate: "6.50",
  loanType: "Interest only",
  additionalLoan: "0",
  renovationCosts: "0",
  furnitureCosts: "0",
  holdingCosts: "0",
  capitalGrowthRate: "5.00",
  capitalizationRate: "3.00",
  inflationRate: "3.00",
  chattelsValue: "45000",
  depreciationMethod: "DV",
  chattelsDepreciationRate: "25",
  buildingDepreciationRate: "0",
  investorTaxRate: "33",
  investorType: "Individual",
  interestDeductibility: "100",
  isNewBuild: false,
  ringFencing: true,
  taxWriteOffPeriod: "1",
  investorDetails: "Person(s)",
  jointWorkIncome: "170,000",
  jointWorkDeductions: "0",
  principalResidence: "900,000",
  amountOwing: "630,000",
  homeLoanRepayments: "58,338",
  livingExpenses: "45,000",
  portfolioProperties: "0",
  portfolioValue: "0",
  taxableIncomeSingle: "120,000",
  rentalIncomeRate: "3.00",
  rentalExpenseRate: "3.00",
  taxableIncomeRate: "3.00",
  livingExpensesRate: "3.00",
  capitalGrowthMode: "growth",
  buildingDepreciation: "0",
  chattelsDepreciation: "11250",
  linkValueFittings: true,
  linkConstructionCost: true,
  rentTimeline: [],
  renovationTimeline: [],
  furnitureTimeline: [],
};